apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repo
  namespace: argocd
  labels:
    name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/heeldev/argocd-repo.git
    targetRevision: HEAD
    path: istio-circuit-breaker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
