---
apiVersion: v1
kind: Pod
metadata:
  name: cli-pod
  labels:
    app: cli-pod
  # annotations:
  #   proxy.istio.io/config: |-
  #     proxyStatsMatcher:
  #       inclusionPrefixes:
  #       - "cluster.outbound"
  #       - "cluster_manager"
  #       - "listener_manager"
  #       - "server"
  #       - "cluster.xds-grpc"
spec:
  serviceAccountName: sa-cli-pod
  containers:
    - name: network-multitool
      command:
        - sleep
        - "86400"
      image: praqma/network-multitool
      imagePullPolicy: IfNotPresent
